version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: citybike
    build:
      context: ./db/
      dockerfile: Dockerfile
      
  backend:
    depends_on:
      - db
    build: ./sda-backend/
    restart: always
    ports:
      - "5221:8080"
    environment:
      DB_HOST: db
      DB_USER: academy
      DB_PW: academy
      DB_PORT: 5432